CREATE TABLE `orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `delivery_date` date DEFAULT NULL,
  `added_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `status_id` tinyint(1) NOT NULL DEFAULT '0',
  `order` text,
  `purchase_price` int(10) unsigned DEFAULT NULL,
  `delivery_time` varchar(255) DEFAULT NULL,
  `contacts` text,
  `notes` text,
  `delivery_address` text,
  `sale_price` int(10) unsigned DEFAULT NULL,
  `assembly_price` int(10) unsigned DEFAULT NULL,
  `delivery_price` int(10) unsigned DEFAULT NULL,
  `fzp` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `status_id` (`status_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8